version: '3'
services:
  redis:
    image: redis:3-alpine
    ports:
      - "6379:6379"
    volumes:
      - ~/data-valeet/redis:/data/redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "~/data-valeet/mongo:/data/db"
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    env_file:
      - ./api/.env
    ports:
      - "4001:8080"
    depends_on:
      - redis
      - mongo
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    env_file:
      - ./app/.env
    ports:
      - "4000:3000"
    depends_on:
      - api